// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt5_BrZyNPK2hoLvBXMDjeyAY9pOmNqsY',
    appId: '1:949510113189:web:52eb3774343e295c2c4a4c',
    messagingSenderId: '949510113189',
    projectId: 'gardensense-cfe37',
    authDomain: 'gardensense-cfe37.firebaseapp.com',
    databaseURL: 'https://gardensense-cfe37-default-rtdb.firebaseio.com',
    storageBucket: 'gardensense-cfe37.appspot.com',
    measurementId: 'G-SS5BJC2JNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1FWHQJg3CkeM3XtSBHmq2ucr_RbKyumQ',
    appId: '1:949510113189:android:3ffbf3a494148a9b2c4a4c',
    messagingSenderId: '949510113189',
    projectId: 'gardensense-cfe37',
    databaseURL: 'https://gardensense-cfe37-default-rtdb.firebaseio.com',
    storageBucket: 'gardensense-cfe37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIuAROBn3oEFY8B1avDOi0-zZd85UKzVI',
    appId: '1:949510113189:ios:4dbf9d870fa86fcb2c4a4c',
    messagingSenderId: '949510113189',
    projectId: 'gardensense-cfe37',
    databaseURL: 'https://gardensense-cfe37-default-rtdb.firebaseio.com',
    storageBucket: 'gardensense-cfe37.appspot.com',
    iosBundleId: 'com.example.garden',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIuAROBn3oEFY8B1avDOi0-zZd85UKzVI',
    appId: '1:949510113189:ios:cc28298b0911306d2c4a4c',
    messagingSenderId: '949510113189',
    projectId: 'gardensense-cfe37',
    databaseURL: 'https://gardensense-cfe37-default-rtdb.firebaseio.com',
    storageBucket: 'gardensense-cfe37.appspot.com',
    iosBundleId: 'com.example.garden.RunnerTests',
  );
}
